import { Footer } from "@/components/footer";
import { Nav } from "../components/nav";
import "./globals.css";
import { Drawer } from "@/components/drawer";
import { ShoppingCart } from "@/components/shopping-cart";
import { CartProvider } from "@/context/cart-context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Drawer>
            <Drawer.Content>
              <Nav />
              <main className="px-10">{children}</main>
              <Footer />
            </Drawer.Content>
            <Drawer.Side>
              <ShoppingCart />
            </Drawer.Side>
          </Drawer>
        </CartProvider>
      </body>
    </html>
  );
}
